import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parseFrontmatter } from '../utils/markdown.js';

interface ArticleMeta {
  file: string;
  title: string;
  summary: string;
  tags: string[];
}

async function readArticles(dir: string): Promise<ArticleMeta[]> {
  let files: string[];
  try {
    files = await readdir(dir);
  } catch {
    return [];
  }

  const articles: ArticleMeta[] = [];
  for (const file of files) {
    if (!file.endsWith('.md')) continue;
    try {
      const raw = await readFile(join(dir, file), 'utf-8');
      const { data } = parseFrontmatter(raw);
      const title = (data.title as string) ?? file.replace(/\.md$/, '');
      const summary = (data.summary as string) ?? '';
      const tags = Array.isArray(data.tags) ? (data.tags as string[]) : [];
      articles.push({ file: file.replace(/\.md$/, ''), title, summary, tags });
    } catch {
      // skip malformed files
    }
  }

  return articles.sort((a, b) => a.title.localeCompare(b.title));
}

export async function rebuildIndex(sessionDir: string, topic: string): Promise<void> {
  const conceptsDir = join(sessionDir, 'wiki', 'concepts');
  const summariesDir = join(sessionDir, 'wiki', 'summaries');

  const [concepts, summaries] = await Promise.all([
    readArticles(conceptsDir),
    readArticles(summariesDir),
  ]);

  const allTags = new Set<string>();
  for (const a of [...concepts, ...summaries]) {
    a.tags.forEach((t) => allTags.add(t));
  }

  const lines: string[] = [
    `# ${topic}`,
    '',
    `_Map of Content for your knowledge base. Auto-generated by \`kb\`._`,
    '',
    `**${concepts.length}** concepts · **${summaries.length}** sources · **${allTags.size}** tags`,
    '',
    '## Concepts',
    '',
  ];

  if (concepts.length === 0) {
    lines.push('_No concept articles yet._', '');
  } else {
    for (const c of concepts) {
      const summary = c.summary ? ` — ${c.summary}` : '';
      lines.push(`- [[concepts/${c.file}|${c.title}]]${summary}`);
    }
    lines.push('');
  }

  lines.push('## Summaries', '');
  if (summaries.length === 0) {
    lines.push('_No source summaries yet._', '');
  } else {
    for (const s of summaries) {
      lines.push(`- [[summaries/${s.file}|${s.title}]]`);
    }
    lines.push('');
  }

  lines.push('## Tags', '');
  if (allTags.size === 0) {
    lines.push('_No tags yet._', '');
  } else {
    const sortedTags = [...allTags].sort();
    lines.push(sortedTags.map((t) => `#${t}`).join(' '), '');
  }

  await writeFile(join(sessionDir, 'wiki', 'index.md'), lines.join('\n'));
}
